name: instant_pay
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  intl_phone_field: ^3.1.0
  intl: ^0.18.0
  animated_text_kit: ^4.2.2
  lottie: ^2.3.2
  share_plus: ^6.3.2
  launch_review: ^3.0.1
  url_launcher: ^6.1.10
  connectivity_plus: ^3.0.4
  fluttertoast: ^8.2.1
  google_mobile_ads: ^2.4.0
  flutter_staggered_grid_view: ^0.4.1
  dotted_border: ^2.0.0+3
  http: ^0.13.4
  facebook_audience_network: ^1.0.1
  flutter_dotenv: ^5.1.0
  # flutter_broadcasts: ^0.3.0
  action_broadcast: ^3.0.2
  easy_localization: ^3.0.1
  switcher_button: ^0.0.4
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/lottie_animation/
    - .env
    - assets/translations/
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Thin.ttf
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
